// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: block.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на обновление блока
type BlockUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vec2                  `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	BlockId       uint32                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Layer         BlockLayer             `protobuf:"varint,3,opt,name=layer,proto3,enum=protocol.BlockLayer" json:"layer,omitempty"`
	Metadata      *JsonMetadata          `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON метаданные для блока
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`     // Тип действия с блоком (mine, use, place, и т.д.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUpdateRequest) Reset() {
	*x = BlockUpdateRequest{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUpdateRequest) ProtoMessage() {}

func (x *BlockUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUpdateRequest.ProtoReflect.Descriptor instead.
func (*BlockUpdateRequest) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *BlockUpdateRequest) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BlockUpdateRequest) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockUpdateRequest) GetLayer() BlockLayer {
	if x != nil {
		return x.Layer
	}
	return BlockLayer_FLOOR
}

func (x *BlockUpdateRequest) GetMetadata() *JsonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BlockUpdateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// Ответ на обновление блока
type BlockUpdateResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BlockId       uint32                 `protobuf:"varint,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Layer         BlockLayer             `protobuf:"varint,5,opt,name=layer,proto3,enum=protocol.BlockLayer" json:"layer,omitempty"`
	Metadata      *JsonMetadata          `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON метаданные для блока
	Effects       []string               `protobuf:"bytes,7,rep,name=effects,proto3" json:"effects,omitempty"`   // Эффекты, связанные с обновлением блока
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUpdateResponseMessage) Reset() {
	*x = BlockUpdateResponseMessage{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUpdateResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUpdateResponseMessage) ProtoMessage() {}

func (x *BlockUpdateResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUpdateResponseMessage.ProtoReflect.Descriptor instead.
func (*BlockUpdateResponseMessage) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockUpdateResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockUpdateResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlockUpdateResponseMessage) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockUpdateResponseMessage) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BlockUpdateResponseMessage) GetLayer() BlockLayer {
	if x != nil {
		return x.Layer
	}
	return BlockLayer_FLOOR
}

func (x *BlockUpdateResponseMessage) GetMetadata() *JsonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BlockUpdateResponseMessage) GetEffects() []string {
	if x != nil {
		return x.Effects
	}
	return nil
}

// Данные о блоке
type BlockData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vec2                  `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	BlockId       uint32                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Metadata      *JsonMetadata          `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON метаданные для блока
	Effects       []string               `protobuf:"bytes,4,rep,name=effects,proto3" json:"effects,omitempty"`   // Визуальные эффекты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *BlockData) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BlockData) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockData) GetMetadata() *JsonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BlockData) GetEffects() []string {
	if x != nil {
		return x.Effects
	}
	return nil
}

// Сообщение с обновлениями блоков
type BlockUpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockData           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUpdateMessage) Reset() {
	*x = BlockUpdateMessage{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUpdateMessage) ProtoMessage() {}

func (x *BlockUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUpdateMessage.ProtoReflect.Descriptor instead.
func (*BlockUpdateMessage) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *BlockUpdateMessage) GetBlocks() []*BlockData {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\bprotocol\x1a\fcommon.proto\"\xd3\x01\n" +
	"\x12BlockUpdateRequest\x12*\n" +
	"\bposition\x18\x01 \x01(\v2\x0e.protocol.Vec2R\bposition\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\rR\ablockId\x12*\n" +
	"\x05layer\x18\x03 \x01(\x0e2\x14.protocol.BlockLayerR\x05layer\x122\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.protocol.JsonMetadataR\bmetadata\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\"\x91\x02\n" +
	"\x1aBlockUpdateResponseMessage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bblock_id\x18\x03 \x01(\rR\ablockId\x12*\n" +
	"\bposition\x18\x04 \x01(\v2\x0e.protocol.Vec2R\bposition\x12*\n" +
	"\x05layer\x18\x05 \x01(\x0e2\x14.protocol.BlockLayerR\x05layer\x122\n" +
	"\bmetadata\x18\x06 \x01(\v2\x16.protocol.JsonMetadataR\bmetadata\x12\x18\n" +
	"\aeffects\x18\a \x03(\tR\aeffects\"\xa0\x01\n" +
	"\tBlockData\x12*\n" +
	"\bposition\x18\x01 \x01(\v2\x0e.protocol.Vec2R\bposition\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\rR\ablockId\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.protocol.JsonMetadataR\bmetadata\x12\x18\n" +
	"\aeffects\x18\x04 \x03(\tR\aeffects\"A\n" +
	"\x12BlockUpdateMessage\x12+\n" +
	"\x06blocks\x18\x01 \x03(\v2\x13.protocol.BlockDataR\x06blocksB.Z,github.com/annel0/mmo-game/internal/protocolb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_block_proto_goTypes = []any{
	(*BlockUpdateRequest)(nil),         // 0: protocol.BlockUpdateRequest
	(*BlockUpdateResponseMessage)(nil), // 1: protocol.BlockUpdateResponseMessage
	(*BlockData)(nil),                  // 2: protocol.BlockData
	(*BlockUpdateMessage)(nil),         // 3: protocol.BlockUpdateMessage
	(*Vec2)(nil),                       // 4: protocol.Vec2
	(BlockLayer)(0),                    // 5: protocol.BlockLayer
	(*JsonMetadata)(nil),               // 6: protocol.JsonMetadata
}
var file_block_proto_depIdxs = []int32{
	4, // 0: protocol.BlockUpdateRequest.position:type_name -> protocol.Vec2
	5, // 1: protocol.BlockUpdateRequest.layer:type_name -> protocol.BlockLayer
	6, // 2: protocol.BlockUpdateRequest.metadata:type_name -> protocol.JsonMetadata
	4, // 3: protocol.BlockUpdateResponseMessage.position:type_name -> protocol.Vec2
	5, // 4: protocol.BlockUpdateResponseMessage.layer:type_name -> protocol.BlockLayer
	6, // 5: protocol.BlockUpdateResponseMessage.metadata:type_name -> protocol.JsonMetadata
	4, // 6: protocol.BlockData.position:type_name -> protocol.Vec2
	6, // 7: protocol.BlockData.metadata:type_name -> protocol.JsonMetadata
	2, // 8: protocol.BlockUpdateMessage.blocks:type_name -> protocol.BlockData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
