// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: common.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType определяет тип сообщения
type MessageType int32

const (
	MessageType_UNKNOWN                MessageType = 0
	MessageType_AUTH                   MessageType = 1
	MessageType_AUTH_RESPONSE          MessageType = 2
	MessageType_CHUNK_DATA             MessageType = 3
	MessageType_CHUNK_REQUEST          MessageType = 4
	MessageType_PING                   MessageType = 5
	MessageType_BLOCK_UPDATE           MessageType = 6
	MessageType_BLOCK_UPDATE_RESPONSE  MessageType = 7
	MessageType_ENTITY_SPAWN           MessageType = 8
	MessageType_ENTITY_MOVE            MessageType = 9
	MessageType_ENTITY_ACTION          MessageType = 10
	MessageType_ENTITY_ACTION_RESPONSE MessageType = 11
	MessageType_CHAT                   MessageType = 12
	MessageType_CHAT_BROADCAST         MessageType = 13
	MessageType_ENTITY_DESPAWN         MessageType = 14
	MessageType_WORLD_EVENT            MessageType = 15
	MessageType_PLAYER_STATS           MessageType = 16
	MessageType_PLAYER_INVENTORY       MessageType = 17
	MessageType_GAME_EVENT             MessageType = 18
	MessageType_SERVER_MESSAGE         MessageType = 19
	MessageType_CHUNK_BATCH_REQUEST    MessageType = 20 // Запрос сразу нескольких чанков
	// Новые типы для delta-обновлений блоков
	MessageType_CHUNK_BLOCK_DELTA         MessageType = 21 // Дельта изменений блоков в чанке
	MessageType_BLOCK_EVENT               MessageType = 22 // Событие изменения блока
	MessageType_SUBSCRIBE_BLOCK_UPDATES   MessageType = 23 // Подписка на обновления блоков
	MessageType_UNSUBSCRIBE_BLOCK_UPDATES MessageType = 24 // Отписка от обновлений блоков
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "AUTH",
		2:  "AUTH_RESPONSE",
		3:  "CHUNK_DATA",
		4:  "CHUNK_REQUEST",
		5:  "PING",
		6:  "BLOCK_UPDATE",
		7:  "BLOCK_UPDATE_RESPONSE",
		8:  "ENTITY_SPAWN",
		9:  "ENTITY_MOVE",
		10: "ENTITY_ACTION",
		11: "ENTITY_ACTION_RESPONSE",
		12: "CHAT",
		13: "CHAT_BROADCAST",
		14: "ENTITY_DESPAWN",
		15: "WORLD_EVENT",
		16: "PLAYER_STATS",
		17: "PLAYER_INVENTORY",
		18: "GAME_EVENT",
		19: "SERVER_MESSAGE",
		20: "CHUNK_BATCH_REQUEST",
		21: "CHUNK_BLOCK_DELTA",
		22: "BLOCK_EVENT",
		23: "SUBSCRIBE_BLOCK_UPDATES",
		24: "UNSUBSCRIBE_BLOCK_UPDATES",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                   0,
		"AUTH":                      1,
		"AUTH_RESPONSE":             2,
		"CHUNK_DATA":                3,
		"CHUNK_REQUEST":             4,
		"PING":                      5,
		"BLOCK_UPDATE":              6,
		"BLOCK_UPDATE_RESPONSE":     7,
		"ENTITY_SPAWN":              8,
		"ENTITY_MOVE":               9,
		"ENTITY_ACTION":             10,
		"ENTITY_ACTION_RESPONSE":    11,
		"CHAT":                      12,
		"CHAT_BROADCAST":            13,
		"ENTITY_DESPAWN":            14,
		"WORLD_EVENT":               15,
		"PLAYER_STATS":              16,
		"PLAYER_INVENTORY":          17,
		"GAME_EVENT":                18,
		"SERVER_MESSAGE":            19,
		"CHUNK_BATCH_REQUEST":       20,
		"CHUNK_BLOCK_DELTA":         21,
		"BLOCK_EVENT":               22,
		"SUBSCRIBE_BLOCK_UPDATES":   23,
		"UNSUBSCRIBE_BLOCK_UPDATES": 24,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Логические этажи блока
type BlockLayer int32

const (
	BlockLayer_FLOOR   BlockLayer = 0
	BlockLayer_ACTIVE  BlockLayer = 1
	BlockLayer_CEILING BlockLayer = 2
)

// Enum value maps for BlockLayer.
var (
	BlockLayer_name = map[int32]string{
		0: "FLOOR",
		1: "ACTIVE",
		2: "CEILING",
	}
	BlockLayer_value = map[string]int32{
		"FLOOR":   0,
		"ACTIVE":  1,
		"CEILING": 2,
	}
)

func (x BlockLayer) Enum() *BlockLayer {
	p := new(BlockLayer)
	*p = x
	return p
}

func (x BlockLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (BlockLayer) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x BlockLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockLayer.Descriptor instead.
func (BlockLayer) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Alias for backward compatibility
type Layer int32

const (
	Layer_LAYER_FLOOR   Layer = 0
	Layer_LAYER_ACTIVE  Layer = 1
	Layer_LAYER_CEILING Layer = 2
)

// Enum value maps for Layer.
var (
	Layer_name = map[int32]string{
		0: "LAYER_FLOOR",
		1: "LAYER_ACTIVE",
		2: "LAYER_CEILING",
	}
	Layer_value = map[string]int32{
		"LAYER_FLOOR":   0,
		"LAYER_ACTIVE":  1,
		"LAYER_CEILING": 2,
	}
)

func (x Layer) Enum() *Layer {
	p := new(Layer)
	*p = x
	return p
}

func (x Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (Layer) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer.Descriptor instead.
func (Layer) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// Общая структура сообщения, которая содержит тип и сериализованные данные
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint32                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Ack           *uint32                `protobuf:"varint,4,opt,name=ack,proto3,oneof" json:"ack,omitempty"`
	AckBits       *uint32                `protobuf:"varint,5,opt,name=ack_bits,json=ackBits,proto3,oneof" json:"ack_bits,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // Сериализованные данные конкретного типа сообщения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *GameMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GameMessage) GetAck() uint32 {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return 0
}

func (x *GameMessage) GetAckBits() uint32 {
	if x != nil && x.AckBits != nil {
		return *x.AckBits
	}
	return 0
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Структура для обработки метаданных в JSON-формате
type JsonMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // JSON-сериализованные метаданные
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonMetadata) Reset() {
	*x = JsonMetadata{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonMetadata) ProtoMessage() {}

func (x *JsonMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonMetadata.ProtoReflect.Descriptor instead.
func (*JsonMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *JsonMetadata) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

// Vec2 - структура для 2D координат
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Vec2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Vec2Float - структура для 2D координат с плавающей точкой
type Vec2Float struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2Float) Reset() {
	*x = Vec2Float{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2Float) ProtoMessage() {}

func (x *Vec2Float) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2Float.ProtoReflect.Descriptor instead.
func (*Vec2Float) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Vec2Float) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2Float) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bprotocol\"\xd8\x01\n" +
	"\vGameMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12\x15\n" +
	"\x03ack\x18\x04 \x01(\rH\x00R\x03ack\x88\x01\x01\x12\x1e\n" +
	"\back_bits\x18\x05 \x01(\rH\x01R\aackBits\x88\x01\x01\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayloadB\x06\n" +
	"\x04_ackB\v\n" +
	"\t_ack_bits\"+\n" +
	"\fJsonMetadata\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"'\n" +
	"\tVec2Float\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y*\xef\x03\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04AUTH\x10\x01\x12\x11\n" +
	"\rAUTH_RESPONSE\x10\x02\x12\x0e\n" +
	"\n" +
	"CHUNK_DATA\x10\x03\x12\x11\n" +
	"\rCHUNK_REQUEST\x10\x04\x12\b\n" +
	"\x04PING\x10\x05\x12\x10\n" +
	"\fBLOCK_UPDATE\x10\x06\x12\x19\n" +
	"\x15BLOCK_UPDATE_RESPONSE\x10\a\x12\x10\n" +
	"\fENTITY_SPAWN\x10\b\x12\x0f\n" +
	"\vENTITY_MOVE\x10\t\x12\x11\n" +
	"\rENTITY_ACTION\x10\n" +
	"\x12\x1a\n" +
	"\x16ENTITY_ACTION_RESPONSE\x10\v\x12\b\n" +
	"\x04CHAT\x10\f\x12\x12\n" +
	"\x0eCHAT_BROADCAST\x10\r\x12\x12\n" +
	"\x0eENTITY_DESPAWN\x10\x0e\x12\x0f\n" +
	"\vWORLD_EVENT\x10\x0f\x12\x10\n" +
	"\fPLAYER_STATS\x10\x10\x12\x14\n" +
	"\x10PLAYER_INVENTORY\x10\x11\x12\x0e\n" +
	"\n" +
	"GAME_EVENT\x10\x12\x12\x12\n" +
	"\x0eSERVER_MESSAGE\x10\x13\x12\x17\n" +
	"\x13CHUNK_BATCH_REQUEST\x10\x14\x12\x15\n" +
	"\x11CHUNK_BLOCK_DELTA\x10\x15\x12\x0f\n" +
	"\vBLOCK_EVENT\x10\x16\x12\x1b\n" +
	"\x17SUBSCRIBE_BLOCK_UPDATES\x10\x17\x12\x1d\n" +
	"\x19UNSUBSCRIBE_BLOCK_UPDATES\x10\x18*0\n" +
	"\n" +
	"BlockLayer\x12\t\n" +
	"\x05FLOOR\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\v\n" +
	"\aCEILING\x10\x02*=\n" +
	"\x05Layer\x12\x0f\n" +
	"\vLAYER_FLOOR\x10\x00\x12\x10\n" +
	"\fLAYER_ACTIVE\x10\x01\x12\x11\n" +
	"\rLAYER_CEILING\x10\x02B.Z,github.com/annel0/mmo-game/internal/protocolb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(MessageType)(0),     // 0: protocol.MessageType
	(BlockLayer)(0),      // 1: protocol.BlockLayer
	(Layer)(0),           // 2: protocol.Layer
	(*GameMessage)(nil),  // 3: protocol.GameMessage
	(*JsonMetadata)(nil), // 4: protocol.JsonMetadata
	(*Vec2)(nil),         // 5: protocol.Vec2
	(*Vec2Float)(nil),    // 6: protocol.Vec2Float
}
var file_common_proto_depIdxs = []int32{
	0, // 0: protocol.GameMessage.type:type_name -> protocol.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
