// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: entity.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Типы сущностей
type EntityType int32

const (
	EntityType_ENTITY_UNKNOWN    EntityType = 0
	EntityType_ENTITY_PLAYER     EntityType = 1
	EntityType_ENTITY_NPC        EntityType = 2
	EntityType_ENTITY_MONSTER    EntityType = 3
	EntityType_ENTITY_ITEM       EntityType = 4
	EntityType_ENTITY_PROJECTILE EntityType = 5
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_UNKNOWN",
		1: "ENTITY_PLAYER",
		2: "ENTITY_NPC",
		3: "ENTITY_MONSTER",
		4: "ENTITY_ITEM",
		5: "ENTITY_PROJECTILE",
	}
	EntityType_value = map[string]int32{
		"ENTITY_UNKNOWN":    0,
		"ENTITY_PLAYER":     1,
		"ENTITY_NPC":        2,
		"ENTITY_MONSTER":    3,
		"ENTITY_ITEM":       4,
		"ENTITY_PROJECTILE": 5,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_entity_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

// Типы действий сущности
type EntityActionType int32

const (
	EntityActionType_ACTION_UNKNOWN     EntityActionType = 0
	EntityActionType_ACTION_INTERACT    EntityActionType = 1
	EntityActionType_ACTION_ATTACK      EntityActionType = 2
	EntityActionType_ACTION_USE_ITEM    EntityActionType = 3
	EntityActionType_ACTION_PICKUP      EntityActionType = 4
	EntityActionType_ACTION_DROP        EntityActionType = 5
	EntityActionType_ACTION_TRADE       EntityActionType = 6
	EntityActionType_ACTION_CRAFT       EntityActionType = 7
	EntityActionType_ACTION_EMOTE       EntityActionType = 8
	EntityActionType_ACTION_RESPAWN     EntityActionType = 9
	EntityActionType_ACTION_BUILD_PLACE EntityActionType = 10
	EntityActionType_ACTION_BUILD_BREAK EntityActionType = 11
)

// Enum value maps for EntityActionType.
var (
	EntityActionType_name = map[int32]string{
		0:  "ACTION_UNKNOWN",
		1:  "ACTION_INTERACT",
		2:  "ACTION_ATTACK",
		3:  "ACTION_USE_ITEM",
		4:  "ACTION_PICKUP",
		5:  "ACTION_DROP",
		6:  "ACTION_TRADE",
		7:  "ACTION_CRAFT",
		8:  "ACTION_EMOTE",
		9:  "ACTION_RESPAWN",
		10: "ACTION_BUILD_PLACE",
		11: "ACTION_BUILD_BREAK",
	}
	EntityActionType_value = map[string]int32{
		"ACTION_UNKNOWN":     0,
		"ACTION_INTERACT":    1,
		"ACTION_ATTACK":      2,
		"ACTION_USE_ITEM":    3,
		"ACTION_PICKUP":      4,
		"ACTION_DROP":        5,
		"ACTION_TRADE":       6,
		"ACTION_CRAFT":       7,
		"ACTION_EMOTE":       8,
		"ACTION_RESPAWN":     9,
		"ACTION_BUILD_PLACE": 10,
		"ACTION_BUILD_BREAK": 11,
	}
)

func (x EntityActionType) Enum() *EntityActionType {
	p := new(EntityActionType)
	*p = x
	return p
}

func (x EntityActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_entity_proto_enumTypes[1].Descriptor()
}

func (EntityActionType) Type() protoreflect.EnumType {
	return &file_entity_proto_enumTypes[1]
}

func (x EntityActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityActionType.Descriptor instead.
func (EntityActionType) EnumDescriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{1}
}

// Данные о сущности
type EntityData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EntityType             `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.EntityType" json:"type,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec2Float             `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Direction     int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Attributes    *JsonMetadata          `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"` // JSON-метаданные атрибутов сущности
	Animation     *string                `protobuf:"bytes,8,opt,name=animation,proto3,oneof" json:"animation,omitempty"`
	Effects       []string               `protobuf:"bytes,9,rep,name=effects,proto3" json:"effects,omitempty"` // Визуальные эффекты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityData) Reset() {
	*x = EntityData{}
	mi := &file_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData) ProtoMessage() {}

func (x *EntityData) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData.ProtoReflect.Descriptor instead.
func (*EntityData) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EntityData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityData) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_ENTITY_UNKNOWN
}

func (x *EntityData) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityData) GetVelocity() *Vec2Float {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityData) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *EntityData) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *EntityData) GetAttributes() *JsonMetadata {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *EntityData) GetAnimation() string {
	if x != nil && x.Animation != nil {
		return *x.Animation
	}
	return ""
}

func (x *EntityData) GetEffects() []string {
	if x != nil {
		return x.Effects
	}
	return nil
}

// Сообщение о создании сущности
type EntitySpawnMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *EntityData            `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySpawnMessage) Reset() {
	*x = EntitySpawnMessage{}
	mi := &file_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySpawnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySpawnMessage) ProtoMessage() {}

func (x *EntitySpawnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySpawnMessage.ProtoReflect.Descriptor instead.
func (*EntitySpawnMessage) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{1}
}

func (x *EntitySpawnMessage) GetEntity() *EntityData {
	if x != nil {
		return x.Entity
	}
	return nil
}

// Сообщение о перемещении сущности
type EntityMoveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityData          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMoveMessage) Reset() {
	*x = EntityMoveMessage{}
	mi := &file_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMoveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMoveMessage) ProtoMessage() {}

func (x *EntityMoveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMoveMessage.ProtoReflect.Descriptor instead.
func (*EntityMoveMessage) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{2}
}

func (x *EntityMoveMessage) GetEntities() []*EntityData {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Сообщение об удалении сущности
type EntityDespawnMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDespawnMessage) Reset() {
	*x = EntityDespawnMessage{}
	mi := &file_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDespawnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDespawnMessage) ProtoMessage() {}

func (x *EntityDespawnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDespawnMessage.ProtoReflect.Descriptor instead.
func (*EntityDespawnMessage) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{3}
}

func (x *EntityDespawnMessage) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityDespawnMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Запрос на действие сущности
type EntityActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    EntityActionType       `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=protocol.EntityActionType" json:"action_type,omitempty"`
	TargetId      *uint64                `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3,oneof" json:"position,omitempty"`
	ItemId        *uint32                `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3,oneof" json:"item_id,omitempty"`
	Params        *JsonMetadata          `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"` // JSON-метаданные параметров действия
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityActionRequest) Reset() {
	*x = EntityActionRequest{}
	mi := &file_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityActionRequest) ProtoMessage() {}

func (x *EntityActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityActionRequest.ProtoReflect.Descriptor instead.
func (*EntityActionRequest) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{4}
}

func (x *EntityActionRequest) GetActionType() EntityActionType {
	if x != nil {
		return x.ActionType
	}
	return EntityActionType_ACTION_UNKNOWN
}

func (x *EntityActionRequest) GetTargetId() uint64 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

func (x *EntityActionRequest) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityActionRequest) GetItemId() uint32 {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return 0
}

func (x *EntityActionRequest) GetParams() *JsonMetadata {
	if x != nil {
		return x.Params
	}
	return nil
}

// Ответ на действие сущности
type EntityActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results       *JsonMetadata          `protobuf:"bytes,3,opt,name=results,proto3" json:"results,omitempty"` // JSON-метаданные результатов действия
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityActionResponse) Reset() {
	*x = EntityActionResponse{}
	mi := &file_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityActionResponse) ProtoMessage() {}

func (x *EntityActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityActionResponse.ProtoReflect.Descriptor instead.
func (*EntityActionResponse) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{5}
}

func (x *EntityActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EntityActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EntityActionResponse) GetResults() *JsonMetadata {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_entity_proto protoreflect.FileDescriptor

const file_entity_proto_rawDesc = "" +
	"\n" +
	"\fentity.proto\x12\bprotocol\x1a\fcommon.proto\"\xdc\x02\n" +
	"\n" +
	"EntityData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.protocol.EntityTypeR\x04type\x12*\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.protocol.Vec2R\bposition\x12/\n" +
	"\bvelocity\x18\x04 \x01(\v2\x13.protocol.Vec2FloatR\bvelocity\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x126\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x16.protocol.JsonMetadataR\n" +
	"attributes\x12!\n" +
	"\tanimation\x18\b \x01(\tH\x00R\tanimation\x88\x01\x01\x12\x18\n" +
	"\aeffects\x18\t \x03(\tR\aeffectsB\f\n" +
	"\n" +
	"_animation\"B\n" +
	"\x12EntitySpawnMessage\x12,\n" +
	"\x06entity\x18\x01 \x01(\v2\x14.protocol.EntityDataR\x06entity\"E\n" +
	"\x11EntityMoveMessage\x120\n" +
	"\bentities\x18\x01 \x03(\v2\x14.protocol.EntityDataR\bentities\"K\n" +
	"\x14EntityDespawnMessage\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x9a\x02\n" +
	"\x13EntityActionRequest\x12;\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x1a.protocol.EntityActionTypeR\n" +
	"actionType\x12 \n" +
	"\ttarget_id\x18\x02 \x01(\x04H\x00R\btargetId\x88\x01\x01\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.protocol.Vec2H\x01R\bposition\x88\x01\x01\x12\x1c\n" +
	"\aitem_id\x18\x04 \x01(\rH\x02R\x06itemId\x88\x01\x01\x12.\n" +
	"\x06params\x18\x05 \x01(\v2\x16.protocol.JsonMetadataR\x06paramsB\f\n" +
	"\n" +
	"_target_idB\v\n" +
	"\t_positionB\n" +
	"\n" +
	"\b_item_id\"|\n" +
	"\x14EntityActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\aresults\x18\x03 \x01(\v2\x16.protocol.JsonMetadataR\aresults*\x7f\n" +
	"\n" +
	"EntityType\x12\x12\n" +
	"\x0eENTITY_UNKNOWN\x10\x00\x12\x11\n" +
	"\rENTITY_PLAYER\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTITY_NPC\x10\x02\x12\x12\n" +
	"\x0eENTITY_MONSTER\x10\x03\x12\x0f\n" +
	"\vENTITY_ITEM\x10\x04\x12\x15\n" +
	"\x11ENTITY_PROJECTILE\x10\x05*\x81\x02\n" +
	"\x10EntityActionType\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fACTION_INTERACT\x10\x01\x12\x11\n" +
	"\rACTION_ATTACK\x10\x02\x12\x13\n" +
	"\x0fACTION_USE_ITEM\x10\x03\x12\x11\n" +
	"\rACTION_PICKUP\x10\x04\x12\x0f\n" +
	"\vACTION_DROP\x10\x05\x12\x10\n" +
	"\fACTION_TRADE\x10\x06\x12\x10\n" +
	"\fACTION_CRAFT\x10\a\x12\x10\n" +
	"\fACTION_EMOTE\x10\b\x12\x12\n" +
	"\x0eACTION_RESPAWN\x10\t\x12\x16\n" +
	"\x12ACTION_BUILD_PLACE\x10\n" +
	"\x12\x16\n" +
	"\x12ACTION_BUILD_BREAK\x10\vB.Z,github.com/annel0/mmo-game/internal/protocolb\x06proto3"

var (
	file_entity_proto_rawDescOnce sync.Once
	file_entity_proto_rawDescData []byte
)

func file_entity_proto_rawDescGZIP() []byte {
	file_entity_proto_rawDescOnce.Do(func() {
		file_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_proto_rawDesc), len(file_entity_proto_rawDesc)))
	})
	return file_entity_proto_rawDescData
}

var file_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_entity_proto_goTypes = []any{
	(EntityType)(0),              // 0: protocol.EntityType
	(EntityActionType)(0),        // 1: protocol.EntityActionType
	(*EntityData)(nil),           // 2: protocol.EntityData
	(*EntitySpawnMessage)(nil),   // 3: protocol.EntitySpawnMessage
	(*EntityMoveMessage)(nil),    // 4: protocol.EntityMoveMessage
	(*EntityDespawnMessage)(nil), // 5: protocol.EntityDespawnMessage
	(*EntityActionRequest)(nil),  // 6: protocol.EntityActionRequest
	(*EntityActionResponse)(nil), // 7: protocol.EntityActionResponse
	(*Vec2)(nil),                 // 8: protocol.Vec2
	(*Vec2Float)(nil),            // 9: protocol.Vec2Float
	(*JsonMetadata)(nil),         // 10: protocol.JsonMetadata
}
var file_entity_proto_depIdxs = []int32{
	0,  // 0: protocol.EntityData.type:type_name -> protocol.EntityType
	8,  // 1: protocol.EntityData.position:type_name -> protocol.Vec2
	9,  // 2: protocol.EntityData.velocity:type_name -> protocol.Vec2Float
	10, // 3: protocol.EntityData.attributes:type_name -> protocol.JsonMetadata
	2,  // 4: protocol.EntitySpawnMessage.entity:type_name -> protocol.EntityData
	2,  // 5: protocol.EntityMoveMessage.entities:type_name -> protocol.EntityData
	1,  // 6: protocol.EntityActionRequest.action_type:type_name -> protocol.EntityActionType
	8,  // 7: protocol.EntityActionRequest.position:type_name -> protocol.Vec2
	10, // 8: protocol.EntityActionRequest.params:type_name -> protocol.JsonMetadata
	10, // 9: protocol.EntityActionResponse.results:type_name -> protocol.JsonMetadata
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_entity_proto_init() }
func file_entity_proto_init() {
	if File_entity_proto != nil {
		return
	}
	file_common_proto_init()
	file_entity_proto_msgTypes[0].OneofWrappers = []any{}
	file_entity_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_proto_rawDesc), len(file_entity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_proto_goTypes,
		DependencyIndexes: file_entity_proto_depIdxs,
		EnumInfos:         file_entity_proto_enumTypes,
		MessageInfos:      file_entity_proto_msgTypes,
	}.Build()
	File_entity_proto = out.File
	file_entity_proto_goTypes = nil
	file_entity_proto_depIdxs = nil
}
