name: "Build and Release"

on:
  # CI для Pull Request'ов и push в основную ветку
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'  # Триггер релиза по тэгу вида vX.Y.Z

jobs:
  # Быстрая проверка тестов на Linux
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run unit-tests
        run: go test ./...

  # Сборка бинарей и публикация в релиз (только для тэгов)
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          # Windows/arm64 официально не поддерживается стандартным Go toolchain'ом
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build ${{ matrix.goos }}-${{ matrix.goarch }} binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -o dist/mmo-game-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mmo-game-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/mmo-game-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mmo-game-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
