// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/protocol/proto/replay.proto

package replay

import (
	events "github.com/annel0/mmo-game/internal/protocol/events"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplayRequest_SortOrder int32

const (
	ReplayRequest_SORT_ORDER_UNSPECIFIED ReplayRequest_SortOrder = 0
	ReplayRequest_SORT_ORDER_ASC         ReplayRequest_SortOrder = 1 // По возрастанию времени
	ReplayRequest_SORT_ORDER_DESC        ReplayRequest_SortOrder = 2 // По убыванию времени
)

// Enum value maps for ReplayRequest_SortOrder.
var (
	ReplayRequest_SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	ReplayRequest_SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x ReplayRequest_SortOrder) Enum() *ReplayRequest_SortOrder {
	p := new(ReplayRequest_SortOrder)
	*p = x
	return p
}

func (x ReplayRequest_SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplayRequest_SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_proto_replay_proto_enumTypes[0].Descriptor()
}

func (ReplayRequest_SortOrder) Type() protoreflect.EnumType {
	return &file_internal_protocol_proto_replay_proto_enumTypes[0]
}

func (x ReplayRequest_SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplayRequest_SortOrder.Descriptor instead.
func (ReplayRequest_SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{0, 0}
}

type EventStatsRequest_StatsGroupBy int32

const (
	EventStatsRequest_STATS_GROUP_BY_UNSPECIFIED EventStatsRequest_StatsGroupBy = 0
	EventStatsRequest_STATS_GROUP_BY_HOUR        EventStatsRequest_StatsGroupBy = 1
	EventStatsRequest_STATS_GROUP_BY_DAY         EventStatsRequest_StatsGroupBy = 2
	EventStatsRequest_STATS_GROUP_BY_EVENT_TYPE  EventStatsRequest_StatsGroupBy = 3
	EventStatsRequest_STATS_GROUP_BY_REGION      EventStatsRequest_StatsGroupBy = 4
)

// Enum value maps for EventStatsRequest_StatsGroupBy.
var (
	EventStatsRequest_StatsGroupBy_name = map[int32]string{
		0: "STATS_GROUP_BY_UNSPECIFIED",
		1: "STATS_GROUP_BY_HOUR",
		2: "STATS_GROUP_BY_DAY",
		3: "STATS_GROUP_BY_EVENT_TYPE",
		4: "STATS_GROUP_BY_REGION",
	}
	EventStatsRequest_StatsGroupBy_value = map[string]int32{
		"STATS_GROUP_BY_UNSPECIFIED": 0,
		"STATS_GROUP_BY_HOUR":        1,
		"STATS_GROUP_BY_DAY":         2,
		"STATS_GROUP_BY_EVENT_TYPE":  3,
		"STATS_GROUP_BY_REGION":      4,
	}
)

func (x EventStatsRequest_StatsGroupBy) Enum() *EventStatsRequest_StatsGroupBy {
	p := new(EventStatsRequest_StatsGroupBy)
	*p = x
	return p
}

func (x EventStatsRequest_StatsGroupBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatsRequest_StatsGroupBy) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_proto_replay_proto_enumTypes[1].Descriptor()
}

func (EventStatsRequest_StatsGroupBy) Type() protoreflect.EnumType {
	return &file_internal_protocol_proto_replay_proto_enumTypes[1]
}

func (x EventStatsRequest_StatsGroupBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatsRequest_StatsGroupBy.Descriptor instead.
func (EventStatsRequest_StatsGroupBy) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{1, 0}
}

// Запрос на воспроизведение событий
type ReplayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Временной диапазон
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Фильтры
	EventTypes []string `protobuf:"bytes,3,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // Типы событий (WorldEvent, BlockEvent, etc.)
	RegionIds  []string `protobuf:"bytes,4,rep,name=region_ids,json=regionIds,proto3" json:"region_ids,omitempty"`    // Регионы
	PlayerIds  []string `protobuf:"bytes,5,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`    // Игроки
	WorldId    string   `protobuf:"bytes,6,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`          // Мир
	// Пагинация
	Limit  int32  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`  // Максимум событий (0 = без ограничений)
	Cursor string `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"` // Курсор для пагинации
	// Сортировка
	SortOrder     ReplayRequest_SortOrder `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3,enum=replay.ReplayRequest_SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ReplayRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ReplayRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *ReplayRequest) GetRegionIds() []string {
	if x != nil {
		return x.RegionIds
	}
	return nil
}

func (x *ReplayRequest) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *ReplayRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *ReplayRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReplayRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ReplayRequest) GetSortOrder() ReplayRequest_SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return ReplayRequest_SORT_ORDER_UNSPECIFIED
}

// Запрос статистики событий
type EventStatsRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StartTime  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	EventTypes []string               `protobuf:"bytes,3,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	RegionIds  []string               `protobuf:"bytes,4,rep,name=region_ids,json=regionIds,proto3" json:"region_ids,omitempty"`
	// Группировка
	GroupBy       EventStatsRequest_StatsGroupBy `protobuf:"varint,5,opt,name=group_by,json=groupBy,proto3,enum=replay.EventStatsRequest_StatsGroupBy" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStatsRequest) Reset() {
	*x = EventStatsRequest{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatsRequest) ProtoMessage() {}

func (x *EventStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatsRequest.ProtoReflect.Descriptor instead.
func (*EventStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{1}
}

func (x *EventStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *EventStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *EventStatsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *EventStatsRequest) GetRegionIds() []string {
	if x != nil {
		return x.RegionIds
	}
	return nil
}

func (x *EventStatsRequest) GetGroupBy() EventStatsRequest_StatsGroupBy {
	if x != nil {
		return x.GroupBy
	}
	return EventStatsRequest_STATS_GROUP_BY_UNSPECIFIED
}

// Ответ со статистикой событий
type EventStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*EventStat           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	TotalEvents   int64                  `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	OldestEvent   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=oldest_event,json=oldestEvent,proto3" json:"oldest_event,omitempty"`
	NewestEvent   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=newest_event,json=newestEvent,proto3" json:"newest_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStatsResponse) Reset() {
	*x = EventStatsResponse{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatsResponse) ProtoMessage() {}

func (x *EventStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatsResponse.ProtoReflect.Descriptor instead.
func (*EventStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{2}
}

func (x *EventStatsResponse) GetStats() []*EventStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *EventStatsResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *EventStatsResponse) GetOldestEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestEvent
	}
	return nil
}

func (x *EventStatsResponse) GetNewestEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.NewestEvent
	}
	return nil
}

// Статистика по группе событий
type EventStat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupKey        string                 `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`        // Ключ группировки
	EventCount      int64                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"` // Количество событий
	PeriodStart     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	EventTypeCounts map[string]int64       `protobuf:"bytes,5,rep,name=event_type_counts,json=eventTypeCounts,proto3" json:"event_type_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Детализация по типам
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventStat) Reset() {
	*x = EventStat{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStat) ProtoMessage() {}

func (x *EventStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStat.ProtoReflect.Descriptor instead.
func (*EventStat) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{3}
}

func (x *EventStat) GetGroupKey() string {
	if x != nil {
		return x.GroupKey
	}
	return ""
}

func (x *EventStat) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *EventStat) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *EventStat) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *EventStat) GetEventTypeCounts() map[string]int64 {
	if x != nil {
		return x.EventTypeCounts
	}
	return nil
}

// Запрос доступных типов событий
type EventTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypesRequest) Reset() {
	*x = EventTypesRequest{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypesRequest) ProtoMessage() {}

func (x *EventTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypesRequest.ProtoReflect.Descriptor instead.
func (*EventTypesRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{4}
}

func (x *EventTypesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *EventTypesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Ответ с доступными типами событий
type EventTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []*EventTypeInfo       `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypesResponse) Reset() {
	*x = EventTypesResponse{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypesResponse) ProtoMessage() {}

func (x *EventTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypesResponse.ProtoReflect.Descriptor instead.
func (*EventTypesResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{5}
}

func (x *EventTypesResponse) GetEventTypes() []*EventTypeInfo {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Информация о типе события
type EventTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Название типа
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`              // Описание
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                         // Количество событий этого типа
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Regions       []string               `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"` // В каких регионах встречается
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeInfo) Reset() {
	*x = EventTypeInfo{}
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeInfo) ProtoMessage() {}

func (x *EventTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_replay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeInfo.ProtoReflect.Descriptor instead.
func (*EventTypeInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_replay_proto_rawDescGZIP(), []int{6}
}

func (x *EventTypeInfo) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventTypeInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EventTypeInfo) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *EventTypeInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *EventTypeInfo) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_internal_protocol_proto_replay_proto protoreflect.FileDescriptor

const file_internal_protocol_proto_replay_proto_rawDesc = "" +
	"\n" +
	"$internal/protocol/proto/replay.proto\x12\x06replay\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$internal/protocol/proto/events.proto\"\xbb\x03\n" +
	"\rReplayRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\x12\x1d\n" +
	"\n" +
	"region_ids\x18\x04 \x03(\tR\tregionIds\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x05 \x03(\tR\tplayerIds\x12\x19\n" +
	"\bworld_id\x18\x06 \x01(\tR\aworldId\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\x12>\n" +
	"\n" +
	"sort_order\x18\t \x01(\x0e2\x1f.replay.ReplayRequest.SortOrderR\tsortOrder\"P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02\"\xa4\x03\n" +
	"\x11EventStatsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\x12\x1d\n" +
	"\n" +
	"region_ids\x18\x04 \x03(\tR\tregionIds\x12A\n" +
	"\bgroup_by\x18\x05 \x01(\x0e2&.replay.EventStatsRequest.StatsGroupByR\agroupBy\"\x99\x01\n" +
	"\fStatsGroupBy\x12\x1e\n" +
	"\x1aSTATS_GROUP_BY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STATS_GROUP_BY_HOUR\x10\x01\x12\x16\n" +
	"\x12STATS_GROUP_BY_DAY\x10\x02\x12\x1d\n" +
	"\x19STATS_GROUP_BY_EVENT_TYPE\x10\x03\x12\x19\n" +
	"\x15STATS_GROUP_BY_REGION\x10\x04\"\xde\x01\n" +
	"\x12EventStatsResponse\x12'\n" +
	"\x05stats\x18\x01 \x03(\v2\x11.replay.EventStatR\x05stats\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x03R\vtotalEvents\x12=\n" +
	"\foldest_event\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\voldestEvent\x12=\n" +
	"\fnewest_event\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vnewestEvent\"\xdb\x02\n" +
	"\tEventStat\x12\x1b\n" +
	"\tgroup_key\x18\x01 \x01(\tR\bgroupKey\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x03R\n" +
	"eventCount\x12=\n" +
	"\fperiod_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12R\n" +
	"\x11event_type_counts\x18\x05 \x03(\v2&.replay.EventStat.EventTypeCountsEntryR\x0feventTypeCounts\x1aB\n" +
	"\x14EventTypeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x85\x01\n" +
	"\x11EventTypesRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"L\n" +
	"\x12EventTypesResponse\x126\n" +
	"\vevent_types\x18\x01 \x03(\v2\x15.replay.EventTypeInfoR\n" +
	"eventTypes\"\xf4\x01\n" +
	"\rEventTypeInfo\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x129\n" +
	"\n" +
	"first_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x18\n" +
	"\aregions\x18\x06 \x03(\tR\aregions2\xd9\x01\n" +
	"\rReplayService\x128\n" +
	"\x06Replay\x12\x15.replay.ReplayRequest\x1a\x15.events.EventEnvelope0\x01\x12F\n" +
	"\rGetEventStats\x12\x19.replay.EventStatsRequest\x1a\x1a.replay.EventStatsResponse\x12F\n" +
	"\rGetEventTypes\x12\x19.replay.EventTypesRequest\x1a\x1a.replay.EventTypesResponseB5Z3github.com/annel0/mmo-game/internal/protocol/replayb\x06proto3"

var (
	file_internal_protocol_proto_replay_proto_rawDescOnce sync.Once
	file_internal_protocol_proto_replay_proto_rawDescData []byte
)

func file_internal_protocol_proto_replay_proto_rawDescGZIP() []byte {
	file_internal_protocol_proto_replay_proto_rawDescOnce.Do(func() {
		file_internal_protocol_proto_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_replay_proto_rawDesc), len(file_internal_protocol_proto_replay_proto_rawDesc)))
	})
	return file_internal_protocol_proto_replay_proto_rawDescData
}

var file_internal_protocol_proto_replay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_protocol_proto_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_protocol_proto_replay_proto_goTypes = []any{
	(ReplayRequest_SortOrder)(0),        // 0: replay.ReplayRequest.SortOrder
	(EventStatsRequest_StatsGroupBy)(0), // 1: replay.EventStatsRequest.StatsGroupBy
	(*ReplayRequest)(nil),               // 2: replay.ReplayRequest
	(*EventStatsRequest)(nil),           // 3: replay.EventStatsRequest
	(*EventStatsResponse)(nil),          // 4: replay.EventStatsResponse
	(*EventStat)(nil),                   // 5: replay.EventStat
	(*EventTypesRequest)(nil),           // 6: replay.EventTypesRequest
	(*EventTypesResponse)(nil),          // 7: replay.EventTypesResponse
	(*EventTypeInfo)(nil),               // 8: replay.EventTypeInfo
	nil,                                 // 9: replay.EventStat.EventTypeCountsEntry
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
	(*events.EventEnvelope)(nil),        // 11: events.EventEnvelope
}
var file_internal_protocol_proto_replay_proto_depIdxs = []int32{
	10, // 0: replay.ReplayRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 1: replay.ReplayRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: replay.ReplayRequest.sort_order:type_name -> replay.ReplayRequest.SortOrder
	10, // 3: replay.EventStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 4: replay.EventStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 5: replay.EventStatsRequest.group_by:type_name -> replay.EventStatsRequest.StatsGroupBy
	5,  // 6: replay.EventStatsResponse.stats:type_name -> replay.EventStat
	10, // 7: replay.EventStatsResponse.oldest_event:type_name -> google.protobuf.Timestamp
	10, // 8: replay.EventStatsResponse.newest_event:type_name -> google.protobuf.Timestamp
	10, // 9: replay.EventStat.period_start:type_name -> google.protobuf.Timestamp
	10, // 10: replay.EventStat.period_end:type_name -> google.protobuf.Timestamp
	9,  // 11: replay.EventStat.event_type_counts:type_name -> replay.EventStat.EventTypeCountsEntry
	10, // 12: replay.EventTypesRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 13: replay.EventTypesRequest.end_time:type_name -> google.protobuf.Timestamp
	8,  // 14: replay.EventTypesResponse.event_types:type_name -> replay.EventTypeInfo
	10, // 15: replay.EventTypeInfo.first_seen:type_name -> google.protobuf.Timestamp
	10, // 16: replay.EventTypeInfo.last_seen:type_name -> google.protobuf.Timestamp
	2,  // 17: replay.ReplayService.Replay:input_type -> replay.ReplayRequest
	3,  // 18: replay.ReplayService.GetEventStats:input_type -> replay.EventStatsRequest
	6,  // 19: replay.ReplayService.GetEventTypes:input_type -> replay.EventTypesRequest
	11, // 20: replay.ReplayService.Replay:output_type -> events.EventEnvelope
	4,  // 21: replay.ReplayService.GetEventStats:output_type -> replay.EventStatsResponse
	7,  // 22: replay.ReplayService.GetEventTypes:output_type -> replay.EventTypesResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_protocol_proto_replay_proto_init() }
func file_internal_protocol_proto_replay_proto_init() {
	if File_internal_protocol_proto_replay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_replay_proto_rawDesc), len(file_internal_protocol_proto_replay_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_proto_replay_proto_goTypes,
		DependencyIndexes: file_internal_protocol_proto_replay_proto_depIdxs,
		EnumInfos:         file_internal_protocol_proto_replay_proto_enumTypes,
		MessageInfos:      file_internal_protocol_proto_replay_proto_msgTypes,
	}.Build()
	File_internal_protocol_proto_replay_proto = out.File
	file_internal_protocol_proto_replay_proto_goTypes = nil
	file_internal_protocol_proto_replay_proto_depIdxs = nil
}
